package controller;

import dao.AdminDAO;
import dao.ClaimDAO;
import dao.AuditLogDAO;
import dao.FoundItemDAO;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import model.Admin;
import model.Claim;
import model.FoundItem;
import database.DBConnection;
import controller.PasswordManager;

import java.io.File;

public class ClaimController {

    // ── FXML fields ──────────────────────────────────────────
    @FXML private Label    itemNameLabel;
    @FXML private Label    itemCategoryLabel;
    @FXML private Label    itemColorLabel;

    @FXML private TextField     claimantNameField;
    @FXML private TextField     claimantIdField;       // student ID — stored in Claim model only
    @FXML private TextField     claimantContactField;
    @FXML private TextField     claimantEmailField;
    @FXML private TextField     remarksField;

    @FXML private PasswordField adminPasswordField;

    @FXML private Label     proofPlaceholder;
    @FXML private ImageView proofPreview;
    @FXML private Button    removeProofButton;
    @FXML private Button    confirmButton;

    // ── State ────────────────────────────────────────────────
    private FoundItem targetItem;
    private String    proofImagePath;

    // ── DAOs ─────────────────────────────────────────────────
    private final AdminDAO     adminDAO  = new AdminDAO();
    private final ClaimDAO     claimDAO  = new ClaimDAO();
    private final FoundItemDAO foundDAO  = new FoundItemDAO();
    private final AuditLogDAO  auditDAO  = new AuditLogDAO();

    // =========================================================
    // Called by AdminController after loading the dialog
    // =========================================================
    public void setTargetItem(FoundItem item) {
        this.targetItem = item;
        itemNameLabel.setText(item.getItemName());
        itemCategoryLabel.setText(item.getCategory());
        itemColorLabel.setText(item.getColor());
    }

    @FXML
    private void handleConfirmClaim() {

        // ── 1. Basic input validation ────────────────────────
        String claimantName  = claimantNameField.getText().trim();
        String studentId     = claimantIdField.getText().trim();
        String contactNum    = claimantContactField.getText().trim();
        String email         = claimantEmailField.getText().trim();
        String typedPassword = adminPasswordField.getText();

        if (contactNum.isEmpty() && email.isEmpty()) {
            showAlert("Validation Error",
                    "Please provide at least a contact number or email address.");
            return;
        }

        if (!email.isEmpty() && !email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            showAlert("Validation Error", "Invalid email format.");
            return;
        }

        if (!contactNum.isEmpty() && !contactNum.matches("^09\\d{9}$")) {
            showAlert("Validation Error",
                    "Invalid contact number format. Use 09XXXXXXXXX.");
            return;
        }

        if (claimantName.isEmpty()) {
            showAlert("Validation Error", "Claimant name is required.");
            return;
        }
        if (typedPassword.isEmpty()) {
            showAlert("Validation Error", "Admin password is required to process a claim.");
            return;
        }
        if (targetItem == null) {
            showAlert("Error", "No item selected for claim.");
            return;
        }

        if (proofImagePath == null) {
            showAlert("Validation Error", "Proof of ownership image is required.");
            return;
        }

        // ── 2. Verify admin password via bcrypt ──────────────
    try {
        Admin admin = adminDAO.getByUsername("admin");

        if (admin == null) {
            showAlert("Error", "Admin account not found. Contact system administrator.");
            return;
        }

        boolean passwordOk = adminDAO.verifyPassword(typedPassword, admin);

        if (!passwordOk) {
            showAlert("Incorrect Password", "Admin password is incorrect. Claim not processed.");
            adminPasswordField.clear();
            return;
        }

        String verifiedBy = admin.getUsername();

        Claim claim = new Claim(
                0,                                            // claimId — auto-generated by DB
                targetItem.getId(),                                  // foundItemId
                claimantName,                                        // claimantName
                studentId.isEmpty()   ? null : studentId,            // studentId (kept in model, not saved to DB)
                contactNum.isEmpty()  ? null : contactNum,           // claimantContactNum
                email.isEmpty()       ? null : email,                // claimantContactEmail
                proofImagePath,                                      // proofImagePath (may be null)
                null,                                                // claimDate — set to CURRENT_DATE by DAO
                verifiedBy,                                          // verifiedBy — real admin username
                remarksField.getText().trim().isEmpty() ? null : remarksField.getText().trim(),       // remarks
                null,                                               // createdAt — set by DB
                null                                                // updatedAt — set by DB
        );


        // Call insert + mark
        boolean ok = claimDAO.insertClaimAndMarkClaimed(claim);
        if (!ok) {
            showAlert("Database Error", "Failed to process claim. Please try again.");
            return;
        }

        // ── 5. Audit log ─────────────────────────────────────
        auditDAO.insertLog(
                targetItem.getId(),
                "Found",
                "Marked Claimed",
                verifiedBy,
                null,
                "{\"item_status\":\"Claimed\",\"claimant\":\"" + claimantName + "\"}"
        );

        // ── 6. Update admin last login timestamp ─────────────
        adminDAO.updateLastLogin(admin.getAdminId());

        showAlert("Success", "Claim processed successfully. Item marked as Claimed.");
        handleClose();
    } catch (DBConnection.NoConnectionException e) {

        showAlert("No Internet",
                "Please connect to the Internet and try again.");

    } catch (Exception e) {

        showAlert("Error",
                "Something went wrong. Please try again.");

        e.printStackTrace();
        }
    }

    // =========================================================
    // Proof image upload
    // =========================================================
    @FXML
    private void handleUploadProof() {

        FileChooser chooser = new FileChooser();
        chooser.setTitle("Select Proof of Ownership");
        chooser.getExtensionFilters().add(
                new FileChooser.ExtensionFilter("Image Files", "*.png", "*.jpg", "*.jpeg")
        );

        File file = chooser.showOpenDialog(proofPlaceholder.getScene().getWindow());

        if (file != null) {
            proofImagePath = file.getAbsolutePath();
            proofPreview.setImage(new Image(file.toURI().toString()));
            proofPreview.setVisible(true);
            proofPlaceholder.setVisible(false);
            removeProofButton.setVisible(true);
            removeProofButton.setManaged(true);
        }
    }

    @FXML
    private void handleRemoveProof() {
        proofImagePath = null;
        proofPreview.setImage(null);
        proofPreview.setVisible(false);
        proofPlaceholder.setVisible(true);
        removeProofButton.setVisible(false);
        removeProofButton.setManaged(false);
    }

    // =========================================================
    // Close dialog
    // =========================================================
    @FXML
    private void handleClose() {
        Stage stage = (Stage) confirmButton.getScene().getWindow();
        stage.close();
    }

    // =========================================================
    // Helper
    // =========================================================
    private void showAlert(String title, String message) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}